apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: events-app
data:
  NODE_ENV: "production"
  PORT: "5000"
  MONGODB_URI: "mongodb://mongodb-0.mongodb.events-app.svc.cluster.local:27017,mongodb-1.mongodb.events-app.svc.cluster.local:27017,mongodb-2.mongodb.events-app.svc.cluster.local:27017/events_management?replicaSet=rs0"
  CORS_ORIGIN: "http://events.local"
