apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: events-app
type: Opaque
stringData:
  JWT_SECRET: 'kubernetes-production-jwt-secret-key-2025'
---
apiVersion: v1
kind: Secret
metadata:
  name: email-credentials
  namespace: events-app
type: Opaque
stringData:
  EMAIL_USER: 'artem2006pax@mail.ru'
  EMAIL_PASS: 'temp-password-change-later'
